import { useState } from 'react';
import { Link, useNavigate, useParams } from '@tanstack/react-router';
import { useQuery } from '@tanstack/react-query';
import { Activity, ArrowLeft, Bell, CalendarDays, CheckCircle2, ClipboardList, Download, Heart, Plus, Share2, TrendingUp, Users } from 'lucide-react';
import { QRCodeSVG } from 'qrcode.react';
import { Button } from '@/components/ui/button'; import { Input } from '@/components/ui/input'; import { Label } from '@/components/ui/label'; import { Textarea } from '@/components/ui/textarea'; import { Switch } from '@/components/ui/switch';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { ChildShell, StatCard, ParentCard, TaskCard, AlertCard, ActivityTimeline, SectionTitle, EmptyState, QuickAdd, Avatar, StatusBadge, SettingsRow, Settings, ShieldCheck, PageSkeleton } from './components';
import { useCareStore } from './store'; import { history, mockApi, type Category } from './data';

export function DashboardPage() {
 const { parents, tasks, alerts } = useCareStore(); const completed = tasks.filter(t => t.status === 'completed').length; const missed = tasks.filter(t => t.status === 'missed').length;
 return <ChildShell title="Good morning, Aditya" subtitle="Here's how your family is doing today." action={<QuickAdd to="/tasks/new" label="New task"/>}>
   <div className="mb-8 grid grid-cols-2 gap-3 sm:gap-4 xl:grid-cols-4"><StatCard icon={Users} label="Parents" value={parents.length} note="In your circle"/><StatCard icon={TrendingUp} label="Completion rate" value={tasks.length ? `${Math.round(completed / tasks.length * 100)}%` : '0%'} note="Today's progress" tone="green"/><StatCard icon={ClipboardList} label="Active tasks" value={tasks.filter(t => t.status === 'pending').length} note="Still to do today" tone="amber"/><StatCard icon={Bell} label="Missed tasks" value={missed} note="Needs attention" tone="red"/></div>
   <div className="grid gap-8 xl:grid-cols-[minmax(0,1.7fr)_minmax(300px,1fr)]"><div className="space-y-9"><section><SectionTitle title="Your people" link="View all" to="/parents"/><div className="grid gap-4 md:grid-cols-2">{parents.map(p => <ParentCard key={p.id} parent={p} tasks={tasks.filter(t=>t.parentId===p.id)}/>)}</div></section><section><SectionTitle title="Today's tasks" link="View all" to="/tasks"/><div className="space-y-3">{tasks.slice(0,4).map(task => <TaskCard key={task.id} task={task} parent={parents.find(p => p.id === task.parentId)}/>)}</div></section></div><div className="space-y-9"><section><SectionTitle title="Needs your attention" link="All alerts" to="/alerts"/><div className="space-y-3">{alerts.length ? alerts.slice(0,2).map(a => <AlertCard key={a.id} alert={a}/>) : <EmptyState icon={Bell} title="No alerts" description="Everything is looking good right now."/>}</div></section><section><SectionTitle title="Recent activity"/><div className="rounded-xl border bg-card p-5 soft-shadow"><ActivityTimeline items={tasks.filter(t => t.status === 'completed').slice(0,4).map(t => ({ title: `${parents.find(p => p.id === t.parentId)?.relationship || 'Parent'} completed ${t.name}`, time: `Today at ${t.time}` }))}/></div></section></div></div>
 </ChildShell>;
}
export function ParentsPage() { const parents = useCareStore(s => s.parents); return <ChildShell title="Your parents" subtitle="Stay close, even from afar." action={<QuickAdd to="/parents/new" label="Add parent"/>}>{parents.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{parents.map(p => <ParentCard key={p.id} parent={p}/>)}</div> : <EmptyState icon={Users} title="No parents linked" description="Invite a parent to begin caring together." action={<Button asChild><Link to="/parents/new">Add parent</Link></Button>}/>}</ChildShell>; }
export function AddParentPage() {
 const [name,setName]=useState(''); const [relationship,setRelationship]=useState('Mom'); const [code,setCode]=useState(''); const addParent=useCareStore(s=>s.addParent);
 const generate=(e:React.FormEvent)=>{e.preventDefault(); const parent=addParent(name.trim(),relationship); setCode(`carecircle://join/${parent.id}`);};
 const download=()=>{ const svg=document.querySelector('#invite-qr svg'); if(!svg)return; const blob=new Blob([new XMLSerializer().serializeToString(svg)],{type:'image/svg+xml'}); const url=URL.createObjectURL(blob); const link=document.createElement('a');link.href=url;link.download=`carecircle-${name.toLowerCase().replace(/\s+/g,'-')}.svg`;link.click();URL.revokeObjectURL(url);};
 const share=async()=>{if(navigator.share) await navigator.share({title:'Join my CareCircle',text:`Scan this code to join ${name}'s CareCircle`,url:code}).catch(()=>{});else if(navigator.clipboard) await navigator.clipboard.writeText(code);};
 return <ChildShell title="Add a parent" subtitle="A simple way to bring your family together."><div className="max-w-xl"><div className="rounded-xl border bg-card p-6 soft-shadow sm:p-8">{!code ? <form onSubmit={generate} className="space-y-6"><div><Label htmlFor="parent-name">Parent name</Label><Input id="parent-name" placeholder="e.g. Meera Tayal" value={name} onChange={e=>setName(e.target.value)} required className="mt-2 h-12"/></div><div><Label htmlFor="relationship">Relationship</Label><Select value={relationship} onValueChange={setRelationship}><SelectTrigger id="relationship" className="mt-2 h-12"><SelectValue/></SelectTrigger><SelectContent>{['Mom','Dad','Grandmother','Grandfather','Other'].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></div><Button type="submit" size="lg" className="h-12 w-full">Generate QR code</Button></form> : <div className="text-center"><div className="mx-auto mb-4 grid size-12 place-items-center rounded-full bg-success-soft text-success"><CheckCircle2/></div><h2 className="text-xl font-bold">Invite {name}</h2><p className="mt-2 text-sm text-muted-foreground">Have {name} scan this code in the parent app.</p><div id="invite-qr" className="mx-auto my-7 w-fit rounded-xl border bg-card p-5"><QRCodeSVG value={code} size={200} fgColor="#2563eb" bgColor="#ffffff"/></div><div className="flex flex-wrap justify-center gap-3"><Button variant="outline" onClick={download}><Download/> Download QR</Button><Button onClick={share}><Share2/> Share invite</Button></div><Button variant="ghost" asChild className="mt-5"><Link to="/parents">Back to parents</Link></Button></div>}</div></div></ChildShell>;
}
export function ParentDetailsPage() {
 const {parentId}=useParams({from:'/parents/$parentId'}); const {parents,tasks}=useCareStore(); const parent=parents.find(p=>p.id===parentId); const parentTasks=tasks.filter(t=>t.parentId===parentId); const {data:weekly,isPending}=useQuery({queryKey:['adherence',parentId],queryFn:()=>mockApi.getWeeklyAdherence(parentId)});
 if(!parent)return <ChildShell title="Parent not found"><EmptyState title="Parent not found" description="This person is not in your circle." action={<Button asChild><Link to="/parents">View parents</Link></Button>}/></ChildShell>;
 return <ChildShell title={parent.name} subtitle={`${parent.relationship} · Last active ${parent.lastActivity}`} action={<Button variant="outline" asChild><Link to="/parents"><ArrowLeft/> Back</Link></Button>}><div className="mb-6 flex items-center gap-4"><Avatar parent={parent} size="large"/><div><div className="font-bold">{parent.completion}% completion</div><div className="text-sm text-muted-foreground">You're doing great together</div></div></div><div className="grid gap-4 sm:grid-cols-3"><StatCard icon={CheckCircle2} label="Completed" value={parentTasks.filter(t=>t.status==='completed').length} tone="green"/><StatCard icon={Bell} label="Missed" value={parentTasks.filter(t=>t.status==='missed').length} tone="red"/><StatCard icon={CalendarDays} label="Pending" value={parentTasks.filter(t=>t.status==='pending').length}/></div><div className="mt-9 grid gap-8 lg:grid-cols-2"><section><SectionTitle title="Upcoming tasks"/><div className="space-y-3">{parentTasks.filter(t=>t.status==='pending').map(t=><TaskCard key={t.id} task={t} parent={parent}/>)}</div></section><section><SectionTitle title="Recent activity"/><div className="rounded-xl border bg-card p-5"><ActivityTimeline items={parentTasks.filter(t=>t.status!=='pending').map(t=>({title:t.name,time:`Today · ${t.time}`,status:t.status}))}/></div></section></div><section className="mt-9"><SectionTitle title="Weekly adherence"/>{isPending ? <PageSkeleton/> : <div className="rounded-xl border bg-card p-6 soft-shadow"><div className="flex h-48 items-end justify-between gap-2 sm:gap-5">{weekly?.map(item=><div key={item.day} className="flex h-full min-w-0 flex-1 flex-col items-center justify-end gap-2"><span className="text-xs font-bold text-muted-foreground">{item.rate}%</span><div className="w-full max-w-14 rounded-t-lg bg-primary/75" style={{height:`${item.rate}%`}}/><span className="text-xs text-muted-foreground">{item.day}</span></div>)}</div></div>}</section></ChildShell>;
}
export function TasksPage() { const {tasks,parents}=useCareStore(); const [filter,setFilter]=useState('All'); const filters=['All','Meals','Medicines','Exercise','Appointments','Wellness']; const visible=tasks.filter(t=>filter==='All'||({Meals:'Meal',Medicines:'Medicine',Exercise:'Exercise',Appointments:'Appointment',Wellness:'Wellness'} as Record<string,string>)[filter]===t.category); return <ChildShell title="Care tasks" subtitle="A little structure makes every day easier." action={<QuickAdd to="/tasks/new" label="New task"/>}><div className="mb-6 flex gap-2 overflow-x-auto pb-2" role="group" aria-label="Filter tasks">{filters.map(f=><Button key={f} variant={filter===f?'default':'outline'} onClick={()=>setFilter(f)} className="shrink-0 rounded-full">{f}</Button>)}</div>{visible.length?<div className="grid gap-3 lg:grid-cols-2">{visible.map(t=><TaskCard key={t.id} task={t} parent={parents.find(p=>p.id===t.parentId)}/>)}</div>:<EmptyState icon={ClipboardList} title="No tasks scheduled" description="Add a task to make the day a little easier." action={<Button asChild><Link to="/tasks/new">Create task</Link></Button>}/>}</ChildShell>; }
export function CreateTaskPage() {
 const navigate=useNavigate(); const {parents,addTask}=useCareStore(); const [name,setName]=useState(''); const [category,setCategory]=useState<Category>('Meal'); const [parentId,setParentId]=useState(parents[0]?.id||''); const [time,setTime]=useState('09:00'); const [repeat,setRepeat]=useState('Daily'); const [notes,setNotes]=useState('');
 const save=(e:React.FormEvent)=>{e.preventDefault();if(!parentId)return;const [hour,minute]=time.split(':').map(Number);addTask({name:name.trim(),category,parentId,time:`${hour%12||12}:${String(minute).padStart(2,'0')} ${hour>=12?'PM':'AM'}`,repeat,notes,detail:notes});navigate({to:'/tasks'});};
 return <ChildShell title="Create a task" subtitle="Set up a thoughtful reminder for someone you love."><form onSubmit={save} className="max-w-2xl space-y-5 rounded-xl border bg-card p-6 soft-shadow sm:p-8"><div><Label htmlFor="task-name">Task name</Label><Input id="task-name" required placeholder="e.g. Take morning medicine" value={name} onChange={e=>setName(e.target.value)} className="mt-2 h-12"/></div><div className="grid gap-5 sm:grid-cols-2"><div><Label htmlFor="category">Category</Label><Select value={category} onValueChange={v=>setCategory(v as Category)}><SelectTrigger id="category" className="mt-2 h-12"><SelectValue/></SelectTrigger><SelectContent>{['Meal','Medicine','Exercise','Appointment','Wellness'].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></div><div><Label htmlFor="assigned-parent">Assigned parent</Label><Select value={parentId} onValueChange={setParentId}><SelectTrigger id="assigned-parent" className="mt-2 h-12"><SelectValue placeholder="Choose a parent"/></SelectTrigger><SelectContent>{parents.map(p=><SelectItem key={p.id} value={p.id}>{p.name}</SelectItem>)}</SelectContent></Select></div><div><Label htmlFor="task-time">Time</Label><Input id="task-time" type="time" required value={time} onChange={e=>setTime(e.target.value)} className="mt-2 h-12"/></div><div><Label htmlFor="repeat">Repeat</Label><Select value={repeat} onValueChange={setRepeat}><SelectTrigger id="repeat" className="mt-2 h-12"><SelectValue/></SelectTrigger><SelectContent>{['Once','Daily','Weekly','Monthly'].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></div></div><div><Label htmlFor="task-notes">Notes <span className="font-normal text-muted-foreground">(optional)</span></Label><Textarea id="task-notes" rows={4} placeholder="Anything helpful for your parent to know" value={notes} onChange={e=>setNotes(e.target.value)} className="mt-2"/></div><div className="flex justify-end gap-3"><Button variant="outline" type="button" asChild><Link to="/tasks">Cancel</Link></Button><Button type="submit" disabled={!parentId}>Save task</Button></div></form></ChildShell>;
}
export function AlertsPage() {const alerts=useCareStore(s=>s.alerts);const dismiss=useCareStore(s=>s.dismissAlert);return <ChildShell title="Alerts" subtitle="The important things, all in one place.">{alerts.length?['Escalation','Missed task','Urgent'].map(type=>{const group=alerts.filter(a=>a.type===type);return group.length?<section className="mb-9" key={type}><SectionTitle title={type==='Urgent'?'Urgent alerts':type==='Missed task'?'Missed tasks':'Escalations'}/><div className="grid gap-3 lg:grid-cols-2">{group.map(a=><AlertCard key={a.id} alert={a} onDismiss={()=>dismiss(a.id)}/>)}</div></section>:null}):<EmptyState icon={Bell} title="No alerts" description="Everything is looking good. We'll let you know if anything needs attention."/>}</ChildShell>}
export function ProfilePage() {const [dark,setDark]=useState(false);const parents=useCareStore(s=>s.parents);const toggle=(checked:boolean)=>{setDark(checked);document.documentElement.classList.toggle('dark',checked)};return <ChildShell title="Profile" subtitle="Your family space, your way."><div className="max-w-2xl space-y-8"><section><SectionTitle title="Your profile"/><div className="rounded-xl border bg-card p-5 soft-shadow"><div className="flex items-center gap-4"><div className="grid size-16 place-items-center rounded-full bg-info-soft text-xl font-bold text-primary">AT</div><div><div className="text-lg font-bold">Aditya Tayal</div><div className="text-sm text-muted-foreground">aditya@example.com</div></div></div></div></section><section><SectionTitle title="Family information"/><div className="rounded-xl border bg-card px-5 soft-shadow"><SettingsRow icon={Users} title="Your circle" detail={`${parents.length} parents connected`}/><SettingsRow icon={Heart} title="CareCircle family" detail="Tayal family"/></div></section><section><SectionTitle title="Settings"/><div className="rounded-xl border bg-card px-5 soft-shadow"><SettingsRow icon={Settings} title="Dark mode" detail="Use a darker appearance"><Switch checked={dark} onCheckedChange={toggle} aria-label="Dark mode"/></SettingsRow><SettingsRow icon={ShieldCheck} title="Privacy" detail="Your family's care stays in your circle"/></div></section><Button variant="outline" asChild className="w-full"><Link to="/">Leave demo</Link></Button></div></ChildShell>}
