"""add_device_tokens_and_notification_deliveries

Revision ID: c8ac09f750aa
Revises: e6ae9f8dec1f
Create Date: 2026-09-25 23:59:43.626008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8ac09f750aa'
down_revision: Union[str, Sequence[str], None] = 'e6ae9f8dec1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('parent_profile_id', sa.Uuid(), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_profile_id'], ['parent_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_tokens_is_active'), 'device_tokens', ['is_active'], unique=False)
    op.create_index(op.f('ix_device_tokens_parent_profile_id'), 'device_tokens', ['parent_profile_id'], unique=False)
    op.create_index(op.f('ix_device_tokens_token'), 'device_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_device_tokens_user_id'), 'device_tokens', ['user_id'], unique=False)
    op.create_table('notification_deliveries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('notification_id', sa.Uuid(), nullable=True),
    sa.Column('device_token_id', sa.Uuid(), nullable=True),
    sa.Column('recipient_token', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_token_id'], ['device_tokens.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_deliveries_device_token_id'), 'notification_deliveries', ['device_token_id'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_notification_id'), 'notification_deliveries', ['notification_id'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_status'), 'notification_deliveries', ['status'], unique=False)
    op.add_column('care_tasks', sa.Column('reminder_interval_minutes', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('care_tasks', sa.Column('escalation_threshold_minutes', sa.Integer(), nullable=False, server_default='15'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('care_tasks', 'escalation_threshold_minutes')
    op.drop_column('care_tasks', 'reminder_interval_minutes')
    op.drop_index(op.f('ix_notification_deliveries_status'), table_name='notification_deliveries')
    op.drop_index(op.f('ix_notification_deliveries_notification_id'), table_name='notification_deliveries')
    op.drop_index(op.f('ix_notification_deliveries_device_token_id'), table_name='notification_deliveries')
    op.drop_table('notification_deliveries')
    op.drop_index(op.f('ix_device_tokens_user_id'), table_name='device_tokens')
    op.drop_index(op.f('ix_device_tokens_token'), table_name='device_tokens')
    op.drop_index(op.f('ix_device_tokens_parent_profile_id'), table_name='device_tokens')
    op.drop_index(op.f('ix_device_tokens_is_active'), table_name='device_tokens')
    op.drop_table('device_tokens')
    # ### end Alembic commands ###
